# PATH: gradle.properties
org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx1G -Dfile.encoding=UTF-8
org.gradle.configureondemand=false
org.gradle.logging.level=quiet

android.useAndroidX=true
android.enableR8.fullMode=false

# Versions
gdxVersion=1.12.1
kotlinVersion=1.9.23
ktxVersion=1.12.1-rc1
serializationVersion=1.6.3
projectVersion=1.0.0
